#!/bin/bash

#
# Puts the sample component into the development directory.
#
# $1 is the name of the component.
# $2 is the $RESTX_HOME directory
# $3 is the partially created component config file
# $4 is the target directory (optional)
# $5 is the module name (optional)
#

#
# This is the Java version of the placement script
#

name="$1"
RESTX_HOME="$2"
COMPONENT_CONF_FILE="$3"

LANGUAGE="Java"
LANGUAGE_ENDING=".java"
LANGUAGES_SRC="$RESTX_HOME/languages/java/src"
RESTX_SRC="src/java"
SAMPLE_COMPONENT_NAME="SampleComponent"
OPTIONAL_TARGET="$4"
OPTIONAL_MODULE="$5"

"$RESTX_HOME"/bin/generic_placement "$name" "$RESTX_HOME" "$LANGUAGE" "$LANGUAGE_ENDING" "$LANGUAGES_SRC" "$RESTX_SRC" "$SAMPLE_COMPONENT_NAME" "$COMPONENT_CONF_FILE" "-" 1 $OPTIONAL_TARGET $OPTIONAL_MODULE


