#!/bin/bash

#
# Puts the sample component into the development directory.
#
# $1 is the name of the component.
# $2 is the $RESTX_HOME directory
# $3 is the partially created component config file
# $4 is the target directory (optional)
#

#
# This is the JavaScript version of the placement script
#

name="$1"
RESTX_HOME="$2"
COMPONENT_CONF_FILE="$3"

LANGUAGE="JavaScript"
LANGUAGE_ENDING=".js"
LANGUAGES_SRC="$RESTX_HOME/languages/javascript/src"
RESTX_SRC="src/javascript"
SAMPLE_COMPONENT_NAME="SampleComponent"
OPTIONAL_TARGET="$4"
OPTIONAL_MODULE="org.mulesoft.restx.component.scripting"
OPTIONAL_IMPORT="JavaScriptComponentWrapper"

if [ -z $OPTIONAL_TARGET ]; then
    OPTIONAL_TARGET="-"
fi

"$RESTX_HOME"/bin/generic_placement "$name" "$RESTX_HOME" "$LANGUAGE" "$LANGUAGE_ENDING" "$LANGUAGES_SRC" "$RESTX_SRC" "$SAMPLE_COMPONENT_NAME" "$COMPONENT_CONF_FILE" ".""$name" 0 $OPTIONAL_TARGET $OPTIONAL_MODULE $OPTIONAL_IMPORT

